-- MySQL Script generated by MySQL Workbench
-- vie 10 abr 2015 14:42:38 VET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facturas_development
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturas_development` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `facturas_development` ;

-- -----------------------------------------------------
-- Table `facturas_development`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas_development`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `apellido` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ci` INT(11) NULL DEFAULT NULL,
  `telefono` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `direccion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `correo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_clientes_on_ci` (`ci` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `facturas_development`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas_development`.`facturas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `precio` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_facturas_on_cliente_id` (`cliente_id` ASC),
  CONSTRAINT `fk_rails_c1da424846`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `facturas_development`.`clientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `facturas_development`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas_development`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `facturas_development`.`factura_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturas_development`.`factura_productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_id` INT(11) NULL DEFAULT NULL,
  `factura_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_factura_productos_on_producto_id` (`producto_id` ASC),
  INDEX `index_factura_productos_on_factura_id` (`factura_id` ASC),
  CONSTRAINT `fk_rails_75eeb2ce19`
    FOREIGN KEY (`factura_id`)
    REFERENCES `facturas_development`.`facturas` (`id`),
  CONSTRAINT `fk_rails_e60d28007e`
    FOREIGN KEY (`producto_id`)
    REFERENCES `facturas_development`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
